version: "3.7"

services:
  nanos:
    #build: .
    image: ghcr.io/ledgerhq/speculos
    volumes:
      - ./bin:/speculos/apps
    ports:
      - "1235:1234" # gdb
      - "5101:5000" # api
      - "40001:40000" # apdu
      - "41001:41000" # vnc
    command: "--model nanos /speculos/apps/app.elf --sdk 2.0 --seed hex:65bfcabf441a68e518e20676efe96c710aa6f7a458c944989280aee0f7683768ad3623c89e641d7561b84e06c859cb11869d9c0ff5500aaa3a66eb1d2702568a --display headless --apdu-port 40000 --vnc-port 41000"
    # Add `--vnc-password "<password>"` for macos users to use built-in vnc client.
